#server
server:  port: 8090
  tomcat:    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:    context-path: /

#spring
spring:  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/    cache: false

#mybatis    
mybatis:  configuration:    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:/mapper/*/*.xml
  
#logging
logging:  level:   com.cy: debug
  file:
   path: D:/1111

#page
page.config: 
    pageSize: 5 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
    
    
    
  
    
    